# Generated by Django 3.2.9 on 2021-12-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20211214_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='destination',
            new_name='donorLocation',
        ),
    ]
