# Generated by Django 3.2.9 on 2021-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_user',
            name='password',
            field=models.CharField(max_length=400, null=True, verbose_name='Password'),
        ),
    ]
